config/routes.rb
Scrapbook::Application.routes.draw do

  root to: 'albums#index'

  get "signup" => "users#new", :as => "signup"
  get "login" => "sessions#new", :as => "login"
  get "logout" => "sessions#destroy", :as => "logout"

  resources :users
  resources :albums do
    resources :photos do
      resources :tags
    end
  end
  resources :sessions
end

app/models/album.rb
class Album < ActiveRecord::Base

  # Define attributes here
  attr_accessible :name, :photos_attributes

  # Define Associations here
  belongs_to :user
  has_many :photos, dependent: :destroy

  # For Nested Forms
  accepts_nested_attributes_for :photos, reject_if: proc{|p| p[:image].blank?}

end

app/models/photo.rb
class Photo < ActiveRecord::Base

  # Define attributes here
  attr_accessible :name, :image, :tags_attributes

  # Define Associations here
  belongs_to :album
  has_many :tags, dependent: :destroy
  has_attached_file :image, 
                     styles: { large: "600x600>", medium: "300x300#", thumb: "100x100>" }, 
                     storage: :s3, 
                     s3_credentials:  AppConfig.s3_creds, 
                     s3_permissions: "public-read", 
                     path: "photos/:style/:id", 
                     bucket: AppConfig.s3_bucket

  # For Nested Forms
  accepts_nested_attributes_for :tags, reject_if: proc{|p| p[:title].blank?}

end

app/models/tag.rb
class Tag < ActiveRecord::Base

  # Define attributes here
  attr_accessible :title

  # Define Associations Here
  belongs_to :photo

  #Define Validations Here
  validates :title, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base

  # Define attributes here
  attr_accessible :auth_token, :email, :first_name, :last_login, :last_name, :login_count,
                :password, :password_confirmation, :password_reset_sent_at, :password_reset_token

  # Define associated things here
  has_secure_password

  # Define Validations here
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, on: :create

  # Define Association here
  has_many :albums, dependent: :destroy

  # Instance Methods
  def sign_in
    increment! :login_count
    touch :last_login
  end

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  respond_to :html, :json, :js

  # Define Actions Here
  def index
    respond_with @albums = current_user.albums.page(params[:page]).per(8)
  end

  def new
    respond_with @album = current_user.albums.new
  end

  def create
    @album = current_user.albums.new(params[:album])

    respond_to do |format|
      if @album.save
        format.html do
          flash[:notice] = "Album Created Successfully"
          redirect_to @album
       end
        format.json {render json: @album}
      else
        flash[:error] = "Error creating album - " + @album.errors.full_messages.join(", ")
        render 'new'
      end
    end
  end

  def show
    @album = Album.find(params[:id])
    @photos = @album.photos
    respond_with @album, @photos
  end

  def destroy
    flash[:notice] = "Album deleted Successfully!!"
    respond_with Album.destroy(params[:id])
  end

  def update
    @album = Album.find params[:id]

    respond_to do |format|
      if @album.update_attributes(params[:album])
        format.html { redirect_to(:back, :notice => 'Album was successfully updated.') }
        format.json { respond_with_bip(@album) }
      else
        format.html { redirect_to :back }
        format.json { respond_with_bip(@album) }
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  # Define filters here
  before_filter :authenticate_user


  # Define private methods here
  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authenticate_user
    unless current_user
      flash[:alert] = "Please login or signup to continue!!"
      redirect_to login_url
    end
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  respond_to :html, :json

  # Define Actions Here
  def create
    @album = Album.find params[:album_id]
    @photo = @album.photos.create params[:photo]
    unless @photo.new_record?
      flash[:notice] = "New Photo Added Successfully"
      redirect_to @photo.album
    end
  end

  def destroy
    Photo.destroy(params[:id])
    flash[:notice] = "Photo deleted Successfully!!"
    redirect_to :back
  end

  def update
    @photo = Photo.find params[:id]

    respond_to do |format|
      if @photo.update_attributes(params[:photo])
        format.html { redirect_to(:back, :notice => 'Tags Added Successfully.') }
        format.json { respond_with_bip(@photo) }
      else
        format.html { redirect_to :back }
        format.json { respond_with_bip(@photo) }
      end
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  # Define Filters here
  skip_before_filter :authenticate_user

  # Define Actions here
  def new
  end

  def create
    user = User.find_by_email params[:email]

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      user.sign_in
      flash[:notice] = "Logged in successfully!!"
      redirect_to root_url
    else
      flash.now.alert = "Invalid email or password"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out successfully!!"
    redirect_to login_url
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  respond_to :html, :json

  #Define Actions Here
  def new
  end

  def create
    respond_with Tag.create params[:tag]
  end

  def destroy
    respond_with Tag.destroy params[:id]
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  respond_to :html, :json

  # Define Filters here
  before_filter :authorize_resource  # Basic Authorization
  skip_before_filter :authenticate_user, only: [:new, :create]

  # Define Actions here
  def new
    respond_with @user = User.new
  end

  def create
    @user = User.new params[:user]
    
    if @user.save
      session[:user_id] = @user.id
      @user.sign_in
      flash[:notice] = "Signed Up Successfully!!"
      redirect_to root_url
    else
      flash[:error] = "Error signing up user - " + @user.errors.full_messages.join(", ")
      render "new"
    end
  end

  def edit
    respond_with @user = User.find(params[:id])
  end

  def update
    @user = User.find params[:id]

    if @user.update_attributes(params[:user])
      flash[:notice] = "User updated Successfully!!"
      redirect_to root_url
    else
      flash[:error] = "Error editing user - " + @user.errors.full_messages.join(", ")
      render 'new'
    end
  end

  # Define Private methods here
  private

  def authorize_resource
    if params[:id] && params[:id].to_i != @current_user.id
      flash[:alert] = "Operation not Authorized!!!"
      redirect_to root_url
    end
  end

end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def flash_class(type)
    case type
      when :alert
        "alert alert-error"
      when :error
        "alert alert-error"
      when :notice
        "alert alert-success"
      else
        ""
    end
  end

end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/_album.html.erb
<div class="span2 well">
  <% unless album.photos.blank? %>
    <%= link_to image_tag(album.photos.sample.image.url(:medium)), album %>
  <% else %>
    <%= link_to image_tag('missing.jpg', width: '300px', height: '300px'), album %>
  <% end %>
  <br />
  <h4 class="text-center"><%= best_in_place album, :name %></h4>
  <p class="text-center"><%= album.photos.count %> Photo(s) inside..</p>
  <center><%= link_to "Delete Album", album, method: :delete, confirm: "Are you sure to remove this Album and its images?" %></center>
</div>

app/views/albums/index.html.erb
<h2 class="text-center">Albums</h2>
<hr />

<div class="span12">
  <div class="span10" id="albums-index">
    <% unless @albums.blank? %>
      <%= render @albums %>
    <% else %>
      <div class="span6 offset2 well">
        <h2 class="text-center">Welcome to Scrapbook!</h2>
        <p class="text-center">You don't have any album yet. You can create one by clicking <b>Add</b> button.</p>
      </div>
    <% end %>
  </div>

  <div class="span1">
    <%= link_to content_tag(:i, " Add", class: 'icon-plus'), new_album_url, class: 'btn btn-success' %>
  </div>
</div>

<div id="paginator">
 <%= paginate(@albums, theme: 'twitter-bootstrap', pagination_class: "pagination-centered", remote: true) if @albums %>
</div>

app/views/albums/index.js.erb
$('div#albums-index').html('<%= escape_javascript render(@albums) %>')
$('#paginator').html('<%= escape_javascript(paginate(@albums, theme: 'twitter-bootstrap', pagination_class: "pagination-centered", remote: true).to_s) %>')

app/views/albums/new.html.erb
<h2>New Album</h2>
<br />

<%= simple_form_for @album do |f| %>
  <%= f.input :name, :input_html => {:required => true} %>
  
  <fieldset>
    <legend>Images</legend>

    <div id="uploadPreview" class="span12"></div>

    <%= f.simple_fields_for :photos_attributes, multipart: true do |p| %>
	<div id="new-image">
      <%= p.input :image, as: :file, label: false, input_html: {name: 'album[photos_attributes][0][image]', class: 'filestyle active_image', :'data-input' => 'false', :'data-classIcon' => 'icon-plus', :'data-classButton' => 'btn btn-success', :'data-buttonText' => 'Add Image'}, wrapper_html: {id: 'add-new-image'}  %>
	  </div>
    <% end %>

  <fieldset>
  <hr />
  <div id='hidden_fields' style='display:none'></div>
  <%= f.submit 'Create Album', class: 'btn btn-primary center' %>
<% end %>

app/views/albums/show.html.erb
<h2 class="text-center"><%= @album.name %>'s Photos(<%= @photos.count %>)</h2>
<%= link_to "Back to Album List", root_path, class: 'pull-right top-10' %>
<hr />

<div class="span12">
  <div class="span10" id="albums-index">
    <% unless @photos.blank? %>
      <%= render @photos %>
    <% else %>
      <div class="span6 offset2 well">
        <h2 class="text-center">Welcome to Scrapbook!</h2>
        <p class="text-center">You don't have any images in this album yet. You can create one by clicking <b>Add</b> button.</p>
      </div>
    <% end %>
  </div>

  <div class="span1">
    <%= link_to content_tag(:i, " Add", class: 'icon-plus'), '#new-photo', class: 'btn btn-success', :'data-toggle' => "modal" %>
  </div>
</div>
<%= render 'photos/new' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <title><%= content_for?(:title) ? yield(:title) : "Scrapbook" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <%= render 'shared/navigation' %>

    <div class="container">
      <div class="alert-container">
        <% flash.each do |type, message| %>
          <%= content_tag :div, class: flash_class(type) do %>
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%= message %>
          <% end %>
        <% end %>
      </div>
    </div>

    <div class="container">
      <div class="span12">
        <%= yield %>
      </div>
    </div>

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/photos/_add_tag.html.erb
<div id=<%="tag_details_#{photo.id}"%> class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Add More Tags</h3>
  </div>

  <br/>

  <div class='offset1'>
    Tags: 
      <% for tag in photo.tags %>
        <%= content_tag :span, class: 'badge' do %>
          <%= tag.title.titleize %>
          <%= link_to content_tag(:i, nil, class: 'icon-remove icon-white'), [photo.album, photo, tag], class: 'remove-tag'%>
        <% end %>
      <% end %>
  </div>
  <br />
  <%= simple_form_for [photo.album, photo] do |f| %>
    <div class='span2 offset1'>
      <%= link_to content_tag(:i, ' Add More Tag', class: 'icon-plus'), '#', class: 'add-m-tags', style: 'cursor:pointer;' %>
    </div>

    <div class="span2">
      <%= f.submit 'Save Tags', class: 'btn btn-primary center' %>
    </div>

  <% end %>
  <br />

</div>

app/views/photos/_new.html.erb
<% new_photo = @album.photos.new %>

<div id="new-photo" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">New Photo</h3>
  </div>

  <%= simple_form_for [@album, new_photo] do |f| %>
    <div class="modal-body">
      <%= f.input :image, label: false, input_html: {class: 'filestyle new_album_photo', :'data-input' => 'false', id: "edit-photo-image"}%>

      <div id='uploadPreview' class="offset1"></div>
    </div>

    <div class="modal-footer">
      <button class="btn btn-primary">Save changes</button>
    </div>

  <% end %>

</div>

app/views/photos/_photo.html.erb
<div class="span2 well">
  <%= link_to content_tag(:i, nil, class: 'icon-remove icon-white'), [photo.album, photo], method: :delete, confirm: "Are you sure to remove this Image from this Album?", class: 'btn btn-danger remove-asset float-over' %>
  <% title = "<h4>#{photo.name}</h4>" %>
  <% title = photo.tags.blank? ? title : title.concat("<p><b>Tags: </b>#{photo.tags.map(&:title).join(', ')}</p>") %>
  <%= link_to image_tag(photo.image.url(:medium)), photo.image.url(:large), rel: "lightbox", title: title %>
  <br />
  <div>
    <h4 class="text-center"><%= best_in_place [photo.album, photo], :name %></h4>
  </div>
  <hr />
  <b>Tags: </b>
  <% unless photo.tags.blank? %>
    <% for tag in photo.tags %>
      <%= content_tag :span, class: 'badge' do %>
        <%= tag.title.titleize %>
        <%= link_to content_tag(:i, nil, class: 'icon-remove icon-white'), [photo.album, photo, tag], class: 'remove-tag'%>
      <% end %>
    <% end %>
  <% end %>
  <%= link_to content_tag(:i, '  Add More', class: 'icon-tag'), "#tag_details_#{photo.id}", class: 'btn btn-success btn-mini' , :'data-toggle' => "modal" %>
</div>
<%= render 'photos/add_tag' , photo: photo %>

app/views/shared/_navigation.html.erb
<div class="navbar navbar-fluid-top">
  <div class="navbar-inner">
    <div class="container-fluid">
      <%= link_to "Scrapbook", root_url, class: 'brand' %>

      <ul class="nav pull-right">
        <% if @current_user %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Hi <%= @current_user.first_name || "User" %>
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to content_tag(:i, " Edit Profile",class: 'icon-user'), edit_user_path(@current_user) %></li>
              <li><%= link_to content_tag(:i, " Logout",class: 'icon-off'), logout_url %></li>
            </ul>
          </li>
        <% else %>
          <li class="divider-vertical"></li>
          <li><%= link_to "Signup", signup_url %></li>
          <li class="divider-vertical"></li>
          <li><%= link_to "Login", login_url %></li>
          <li class="divider-vertical"></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h2>Edit User</h2>
<hr />

<%= simple_form_for @user do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :email %>

  <%= f.submit 'Update User', class: 'btn btn-primary' %>

  <hr />

  <%= link_to "Back to Home Page", root_path %>
<% end %>

app/views/users/new.html.erb
<h2>Sign Up</h2>
<br />

<%= simple_form_for @user do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :email %>
  <%= f.input :password %>
  <%= f.input :password_confirmation %>

  <%= f.button :submit, class: 'btn btn-primary' %>
<% end %>